//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFirewallNotifier.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFirewallNotifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In/Out.
        /// </summary>
        public static string FW_DIR_BOTH {
            get {
                return ResourceManager.GetString("FW_DIR_BOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In.
        /// </summary>
        public static string FW_DIR_IN {
            get {
                return ResourceManager.GetString("FW_DIR_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Out.
        /// </summary>
        public static string FW_DIR_OUT {
            get {
                return ResourceManager.GetString("FW_DIR_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string FW_PROFILE_ALL {
            get {
                return ResourceManager.GetString("FW_PROFILE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Domain.
        /// </summary>
        public static string FW_PROFILE_DOMAIN {
            get {
                return ResourceManager.GetString("FW_PROFILE_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Private.
        /// </summary>
        public static string FW_PROFILE_PRIVATE {
            get {
                return ResourceManager.GetString("FW_PROFILE_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Public.
        /// </summary>
        public static string FW_PROFILE_PUBLIC {
            get {
                return ResourceManager.GetString("FW_PROFILE_PUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow.
        /// </summary>
        public static string FW_RULE_ALLOW {
            get {
                return ResourceManager.GetString("FW_RULE_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Block.
        /// </summary>
        public static string FW_RULE_BLOCK {
            get {
                return ResourceManager.GetString("FW_RULE_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        public static System.Drawing.Icon ICON_SHIELD {
            get {
                object obj = ResourceManager.GetObject("ICON_SHIELD", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow: a firewall rule will be created for the concerned application,
        ///except if you tick the checkbox below to allow it temporarily..
        /// </summary>
        public static string MSG_ALLOW {
            get {
                return ResourceManager.GetString("MSG_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignore: adds the concerned application to the exceptions list
        ///to prevent any further notification, or creates a blocking rule for the Windows Firewall depending on which option you choosed..
        /// </summary>
        public static string MSG_BLOCK {
            get {
                return ResourceManager.GetString("MSG_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows Firewall Notifier - Error.
        /// </summary>
        public static string MSG_DLG_ERR_TITLE {
            get {
                return ResourceManager.GetString("MSG_DLG_ERR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows Firewall Notifier.
        /// </summary>
        public static string MSG_DLG_TITLE {
            get {
                return ResourceManager.GetString("MSG_DLG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The corresponding rule has been created..
        /// </summary>
        public static string MSG_RULE_CREATED {
            get {
                return ResourceManager.GetString("MSG_RULE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are going to remove the selected firewall rule.
        ///Continue?.
        /// </summary>
        public static string MSG_RULE_DELETE {
            get {
                return ResourceManager.GetString("MSG_RULE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The corresponding rule has not been created..
        /// </summary>
        public static string MSG_RULE_FAILED {
            get {
                return ResourceManager.GetString("MSG_RULE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The temporary rule could not be removed.
        ///The application outgoing connections are still allowed.
        ///Please check the Windows firewall for a rule named {0}..
        /// </summary>
        public static string MSG_RULE_RM_FAILED {
            get {
                return ResourceManager.GetString("MSG_RULE_RM_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to temporary allow this application..
        /// </summary>
        public static string MSG_RULE_TMP_FAILED {
            get {
                return ResourceManager.GetString("MSG_RULE_TMP_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom Rule - {0}.
        /// </summary>
        public static string RULE_NAME_FORMAT {
            get {
                return ResourceManager.GetString("RULE_NAME_FORMAT", resourceCulture);
            }
        }
    }
}
