//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wokhan.WindowsFirewallNotifier.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wokhan.WindowsFirewallNotifier.Common.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In/Out.
        /// </summary>
        public static string FW_DIR_BOTH {
            get {
                return ResourceManager.GetString("FW_DIR_BOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string FW_DIR_IN {
            get {
                return ResourceManager.GetString("FW_DIR_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string FW_DIR_OUT {
            get {
                return ResourceManager.GetString("FW_DIR_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FW_PROFILE_ALL {
            get {
                return ResourceManager.GetString("FW_PROFILE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string FW_PROFILE_DOMAIN {
            get {
                return ResourceManager.GetString("FW_PROFILE_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string FW_PROFILE_PRIVATE {
            get {
                return ResourceManager.GetString("FW_PROFILE_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string FW_PROFILE_PUBLIC {
            get {
                return ResourceManager.GetString("FW_PROFILE_PUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string FW_RULE_ALLOW {
            get {
                return ResourceManager.GetString("FW_RULE_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string FW_RULE_BLOCK {
            get {
                return ResourceManager.GetString("FW_RULE_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_SHIELD {
            get {
                object obj = ResourceManager.GetObject("ICON_SHIELD", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow: a firewall rule will be created for the concerned application,
        ///except if you tick the checkbox below to allow it temporarily..
        /// </summary>
        public static string MSG_ALLOW {
            get {
                return ResourceManager.GetString("MSG_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore: adds the concerned application to the exceptions list
        ///to prevent any further notification, or creates a blocking rule for the Windows Firewall depending on which option you choosed..
        /// </summary>
        public static string MSG_BLOCK {
            get {
                return ResourceManager.GetString("MSG_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Firewall Notifier - Error.
        /// </summary>
        public static string MSG_DLG_ERR_TITLE {
            get {
                return ResourceManager.GetString("MSG_DLG_ERR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Firewall Notifier.
        /// </summary>
        public static string MSG_DLG_TITLE {
            get {
                return ResourceManager.GetString("MSG_DLG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write to log file. Please make sure the log file is not in use by another program..
        /// </summary>
        public static string MSG_LOG_FAILED {
            get {
                return ResourceManager.GetString("MSG_LOG_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corresponding rule has been created..
        /// </summary>
        public static string MSG_RULE_CREATED {
            get {
                return ResourceManager.GetString("MSG_RULE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to remove the selected firewall rule.
        ///Continue?.
        /// </summary>
        public static string MSG_RULE_DELETE {
            get {
                return ResourceManager.GetString("MSG_RULE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corresponding rule has not been created..
        /// </summary>
        public static string MSG_RULE_FAILED {
            get {
                return ResourceManager.GetString("MSG_RULE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A protocol must be specified in order to be able to base rules on ports..
        /// </summary>
        public static string MSG_RULE_PROTOCOL_NEEDED {
            get {
                return ResourceManager.GetString("MSG_RULE_PROTOCOL_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temporary rule could not be removed.
        ///The application outgoing connections are still allowed.
        ///Please check the Windows Firewall for a rule named {0}..
        /// </summary>
        public static string MSG_RULE_RM_FAILED {
            get {
                return ResourceManager.GetString("MSG_RULE_RM_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to temporary allow this application..
        /// </summary>
        public static string MSG_RULE_TMP_FAILED {
            get {
                return ResourceManager.GetString("MSG_RULE_TMP_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleManager cannot be run manually..
        /// </summary>
        public static string MSG_RULEMANAGER_ARGUMENTS_ERR {
            get {
                return ResourceManager.GetString("MSG_RULEMANAGER_ARGUMENTS_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Rule - {0}.
        /// </summary>
        public static string RULE_NAME_FORMAT {
            get {
                return ResourceManager.GetString("RULE_NAME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple matches found..
        /// </summary>
        public static string SERVICES_UNDEF {
            get {
                return ResourceManager.GetString("SERVICES_UNDEF", resourceCulture);
            }
        }
    }
}
